### ISSUE TITLE
Panic with 'called `Option::unwrap()` on a `None` value' in mcu.rs:383:48 on a real-world image

### ISSUE THREAD

**Issue by Shnatsel** [etemesi254/zune-jpeg#19]
The attached image causes zune-jpeg to panic when decoding it: [Crocosmia_by_sirpecangum](https://user-images.githubusercontent.com/291257/182029422-455570eb-ffcc-4a53-bd64-2fcad55d081f.jpg)

Backtrace:

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/shnatsel/Code/zune-jpeg/src/mcu.rs:383:48
stack backtrace:
   0: rust_begin_unwind
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/panicking.rs:142:14
   2: core::panicking::panic
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/panicking.rs:48:5
   3: core::option::Option<T>::unwrap
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/option.rs:755:21
   4: zune_jpeg::mcu::<impl zune_jpeg::decoder::Decoder>::decode_mcu_ycbcr_baseline::{{closure}}
             at /home/shnatsel/Code/zune-jpeg/src/mcu.rs:383:34
   5: scoped_threadpool::Pool::scoped
             at /home/shnatsel/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped_threadpool-0.1.9/src/lib.rs:181:9
   6: zune_jpeg::mcu::<impl zune_jpeg::decoder::Decoder>::decode_mcu_ycbcr_baseline
             at /home/shnatsel/Code/zune-jpeg/src/mcu.rs:245:9
   7: zune_jpeg::decoder::Decoder::decode_internal
             at /home/shnatsel/Code/zune-jpeg/src/decoder.rs:428:13
   8: zune_jpeg::decoder::Decoder::decode_file
             at /home/shnatsel/Code/zune-jpeg/src/decoder.rs:220:9
   9: zune_jpeg_bench::main
             at ./src/main.rs:9:5
  10: core::ops::function::FnOnce::call_once
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/ops/function.rs:248:5
```

Tested on commit d2aaf010d67b8ac715a48fc92714f508c2a6966d (latest as of this writing)

**Comment by Shnatsel** [comment]
This is the last panic I have seen on my collection of real-world images, which totals something like 60,000 JPEG files.
