### ISSUE TITLE
Panics on decoding files generated by fuzzers for other decoders

### ISSUE THREAD

**Issue by Shnatsel** [etemesi254/zune-jpeg#8]
I have decoded the [AFL-generated set](https://lcamtuf.coredump.cx/afl/demo/) of exotic JPEGs when fuzzing libjpeg-turbo, as well as the files generated by AFL when targeting the `jpeg-decoder` crate. Decoding these files causes multiple panics in `zune-jpeg`.

The set of files triggering the panics is attached: [jpeg_fuzzing_seeds.tar.gz](https://github.com/etemesi254/zune-jpeg/files/8780001/jpeg_fuzzing_seeds.tar.gz)

Aside of being interesting test cases, these files can also be used to kickstart fuzzing - simply put them into `fuzz/corpus/decode_buffer` and run the fuzzer as usual. This should provide much better coverage than starting from scratch.

**Comment by etemesi254** [comment]
Just an update.

Most panics have been fixed in version 0.1.3, but I would like to keep this issue open for future fuzz errors/panics

**Comment by Shnatsel** [comment]
I'm seeing panics on the fuzzer still, for example `panicked at 'attempt to subtract with overflow', zune-jpeg/src/headers.rs:138:17`

That may not show up in release mode, but fuzzing deliberately enables debug assertions, which includes integer overflow/underflow checks.

**Comment by etemesi254** [comment]
Yeah that cropped up due to a bug in that fixed a  previous issue.

It's fixed now (master branch) and fuzzing should now take a while before it crashes.

Thanks for the heads up.

**Comment by Shnatsel** [comment]
Here's a new one: `thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /home/shnatsel/Code/zune-jpeg/src/mcu.rs:326:48`

The file to trigger it: [yet-another-panic.jpeg](https://user-images.githubusercontent.com/291257/173666352-0829b41c-41e6-46e9-85c7-cf38405d8d21.jpeg)

**Comment by etemesi254** [comment]
Could you be kind enough to share the corpus you are testing with?

It seems I do not have that with me.

Also fix coming in a few

**Comment by Shnatsel** [comment]
The corpus is just the [jpeg_fuzzing_seeds.tar.gz](https://github.com/etemesi254/zune-jpeg/files/8780001/jpeg_fuzzing_seeds.tar.gz) I shared in the first message of the thread, placed in the `fuzz/corpus/decode_buffer` directory so that the fuzzer can use it as a starting point.

That's how fuzzers were originally meant to be used, in fact! The notion of synthesizing JPEGs out of thin air, without giving the fuzzer a broad sample of JPEGs with various modes and encodings, is [more of a happy accident](https://lcamtuf.blogspot.com/2014/11/pulling-jpegs-out-of-thin-air.html) and is not how the tool was originally meant to be used.

**Comment by etemesi254** [comment]
Sorry my bad, I thought I was already fuzzing on this corpus.

I'll ping this issue once all test cases work, for a new release.

**Comment by Shnatsel** [comment]
You can handle errors without using the `String` type and the associated allocation, but you will not be able to include arbitrary text determined at runtime. You'll only be able to use hardcoded strings.

10 nanoseconds sounds about right for the cost of an allocation, but it is a tiny amount. Unless you're returning a String in a hot loop, this will never matter in practice. I recall eliminating thousands of allocations per second in jpeg-decoder and seeing near-zero performance difference, so I would not worry about that.

I can help profile before and after the change if you need help evaluating it.

**Comment by etemesi254** [comment]
The unsafe code i was trying to remove was https://github.com/etemesi254/zune-jpeg/blob/050a2327c9eee9cc435a91f6588d67cfc661195b/src/mcu.rs#L248-L259 

 to be https://gist.github.com/etemesi254/e2cc65afbdf49b9b402506a9c9ff6802#file-mcu-rs-L248-L281


It's the only unsafe code left that isn't platform specific intrinsics which can be disabled by turning off the `x86` feature, so that means we can do a `cfg[not(feature="x86)]`+ `#[forbid(unsafe_code)]`  but its a 3-7% regression on the benchark.


The  invariant unsafe code had to uphold were checked earlier, (`check_tables()` method), so it was kind of like manual loop hoisting hence why it was like that

**Comment by Shnatsel** [comment]
Was it 3-7% regression in end-to-end decoding performance, or should I run some specific benchmark to reproduce it?

I can think of a few things to try - outlining the error reporting into functions annotated with `#[cold]`, for example. 

But before I do, I'd like to understand how frequently this code is executed. 3-7% is low enough that it could be just spurious due to changes in the code layout, and not any genuine change to the performance of the code. Also, do all of these lookups really have to happen on every iteration of the loop, or can we perhaps cache them somehow?

**Comment by etemesi254** [comment]
## How many checks per image
A typical 1920 * 1080 image

First we multiply the image by its dimensions =  2073600

Then we multiply the dimensions by the number of components , a typical image has 3(Y, Cb,Cr that get converted to R,G,B) = 6220800

JPEG divides an image into blocks of 8 by 8 pixels, called MCUs(Minimum Coded Units), the total dimension of an MCU is 64, so we can divide the pixels by 64= 97200

And for every MCU we do two lookups (DC and AC), so we again multiply by 2 = 194,400.think it c

## Why it must happen on every iteration of the loop

```rust
for y in 0..mcu_height{
      for x in 0..mcu_width{
          for c in 0..number_components{
              take table for component
          }
      }
}
```

The order of the loop cannot be changed as the spec mandates it to be like that

## Why I'm sure it caused the regression
Changing this

```rust
 self
     .dc_huffman_tables
      .get(component.dc_huff_table)
      .ok_or_else(|| {
          DecodeErrors::HuffmanDecode(format!(
              "No Huffman DC table for component {:?} ",
              component.component_id
          ))
      })?
      .as_ref()
      .ok_or_else(|| {
          DecodeErrors::HuffmanDecode(format!(
              "No DC table for component {:?}",
              component.component_id
          ))
      })?;
```

To this 
```rust

self.dc_huffman_tables[component.dc_huff_table & 3]
      .as_ref()
      .ok_or_else(|| {
          DecodeErrors::HuffmanDecode(format!(
              "No DC table for component {:?}",
              component.component_id
          ))
      })?;
```
Caused 3% perf jump

**Comment by etemesi254** [comment]
Update, went ahead and did it https://github.com/etemesi254/zune-jpeg/commit/7496ae86f0f1c735ab3856ab62266abc618081fe and https://github.com/etemesi254/zune-jpeg/commit/732a61b0e0785a4aa711fa0462181e520286f27a.

Now the only unsafe is in sse/avx2 routines for post processing,

**Comment by Shnatsel** [comment]
I've run the fuzzer for 5 minutes with 4 threads on v0.1.4 and found a panic:

`thread '<unnamed>' panicked at 'Slice to small cannot write', /home/shnatsel/Code/zune-jpeg/src/color_convert/avx.rs:88:10`

The file triggering this is attached:
[crash-0abdc9186d3f455eebddb86dcc318238d20dba73](https://user-images.githubusercontent.com/291257/174493891-778bb8d4-c4fe-4edb-a36a-77b9882734a6.jpg)

**Comment by etemesi254** [comment]
Acknowledged

**Comment by etemesi254** [comment]
> I've run the fuzzer for 5 minutes with 4 threads on v0.1.4 and found a panic:
> 
> `thread '<unnamed>' panicked at 'Slice to small cannot write', /home/shnatsel/Code/zune-jpeg/src/color_convert/avx.rs:88:10`
> 
> The file triggering this is attached: [crash-0abdc9186d3f455eebddb86dcc318238d20dba73](https://user-images.githubusercontent.com/291257/174493891-778bb8d4-c4fe-4edb-a36a-77b9882734a6.jpg)

This is fixed(some new commits landed)  but it presents an interesting case of the spec vs the reference implementation.

So the image above isn't valid according to the jpeg spec, because of the following phrase in the spec, 

### F.2.2.5: NextBit Procedure which says

> The only valid marker which may occur within the Huffman coded data is the RSTm marker.

This image (and a lot of fuzz generated images) have this property and the solution should be to report to the user that you have a corrupt image, but libjpeg-turbo tries to parse them as headers, for some reason I really don't understand.

So to ensure compatibility, I decided to do as they do.

**Comment by Shnatsel** [comment]
The following file causes a panic superficially similar to #11:

[crash-faff0f2581d3b225f3552f416b546bf7bcbdbbe8](https://user-images.githubusercontent.com/291257/177013749-e8aab970-ac01-4734-bb2f-e2b43acb78c6.jpg)

Tested on commit 1f92bac5c8ef614208e65f4d72665f650bb0cb4b

**Comment by etemesi254** [comment]
I believe that is related to https://github.com/etemesi254/zune-jpeg/issues/11

**Comment by Shnatsel** [comment]
[The input in the previous message by me](https://user-images.githubusercontent.com/291257/177013749-e8aab970-ac01-4734-bb2f-e2b43acb78c6.jpg) still causes a panic: 

`thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/shnatsel/Code/zune-jpeg/src/mcu_prog.rs:305:90`

**Comment by etemesi254** [comment]
Do other decoders complain about this?

**Comment by Shnatsel** [comment]
djpeg does complain:

```
Corrupt JPEG data: 1 extraneous bytes before marker 0xdb
Unsupported marker type 0x18
```
jpeg-decoder also doesn't decode it, but it returns an error instead of panicking.

**Comment by Shnatsel** [comment]
And another one causing panic at a slightly different place in mcu_prog.rs: [crash-b96a4b3c805261b156103da43bdab1a4eb7ed527](https://user-images.githubusercontent.com/291257/182031913-89ea1564-2f0c-4cae-bc67-8e9249a72712.jpg)

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/shnatsel/Code/zune-jpeg/src/mcu_prog.rs:299:26
```

This one _is_ decoded by djpeg, although being fuzzer-generated it is obviously corrupt.

**Comment by etemesi254** [comment]
> And another one causing panic at a slightly different place in mcu_prog.rs: [crash-b96a4b3c805261b156103da43bdab1a4eb7ed527](https://user-images.githubusercontent.com/291257/182031913-89ea1564-2f0c-4cae-bc67-8e9249a72712.jpg)
> 
> ```
> thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/shnatsel/Code/zune-jpeg/src/mcu_prog.rs:299:26
> ```
> 
> This one _is_ decoded by djpeg, although being fuzzer-generated it is obviously corrupt.

Fixed in latest version.

Also pushed to crates.io (v0.1.5)

**Comment by Shnatsel** [comment]
Here's another panic: [ya-zune-jpeg-mcu-panic.jpg](https://user-images.githubusercontent.com/291257/183299376-ef158177-f973-4db0-b3d3-47fef32d73eb.jpg)

```
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /home/shnatsel/Code/zune-jpeg/src/mcu_prog.rs:304:48
```

**Comment by Shnatsel** [comment]
And here's my current corpus, so you could run the fuzzer yourself: [jpeg_fuzzing_seeds_2.tar.gz](https://github.com/etemesi254/zune-jpeg/files/9277079/jpeg_fuzzing_seeds_2.tar.gz)

Place the contents in `zune-jpeg/fuzz/corpus/decode_buffer/` folder and run `cargo +nightly fuzz run decode_buffer`

**Comment by etemesi254** [comment]
> Here's another panic: [ya-zune-jpeg-mcu-panic.jpg](https://user-images.githubusercontent.com/291257/183299376-ef158177-f973-4db0-b3d3-47fef32d73eb.jpg)
> 
> ```
> thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /home/shnatsel/Code/zune-jpeg/src/mcu_prog.rs:304:48
> ```

Fixed

**Comment by etemesi254** [comment]
> And here's my current corpus, so you could run the fuzzer yourself: [jpeg_fuzzing_seeds_2.tar.gz](https://github.com/etemesi254/zune-jpeg/files/9277079/jpeg_fuzzing_seeds_2.tar.gz)
> 
> Place the contents in `zune-jpeg/fuzz/corpus/decode_buffer/` folder and run `cargo +nightly fuzz run decode_buffer`

Currently can't fuzz as I'm debugging ffmpeg, those two aren't compatible, so fixing errors arising from this may take some time.
